apiVersion: apps/v1
kind: Deployment
metadata:
  name: eternal-portal-app-deployment
  labels:
    app: eternal-portal-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eternal-portal-app
  template:
    metadata:
      labels:
        app: eternal-portal-app
    spec:
      containers:
        - name: eternal-portal-app
          image: 814706224440.dkr.ecr.us-east-1.amazonaws.com/eternal-portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: eternal-portal

---
apiVersion: v1
kind: Service
metadata:
  name: eternal-portal-app-service
spec:
  selector:
    app: eternal-portal-app
  ports:
  - name: eternal-portal-app-service-port
    protocol: TCP
    port: 3000
    targetPort: eternal-portal
  type: LoadBalancer 
