apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: 893121324602.dkr.ecr.us-east-2.amazonaws.com/eternal-portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8094

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: demo-app-service-port
    protocol: TCP
    port: 8094
    targetPort: 8094
  type: LoadBalancer 
