apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ETXdOekUwTVRVMU5Gb1hEVE16TURNd05ERTBNVFUxTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGZTCjdKTnFMN1Y1QkJRUnVyT3dsUEZCZlZod1cxRHZqRzlBQkM3RHFPdnRWN05pYThqQW5VNGFIUVVIeEJSTFNkVjcKMkRYaUx0cy9qaTBocTVzVEh6WXpHWVd6UFJHcTJFay9rWllEbDB1bk8zMHpBWURPOVRYQXJvWVZPcFRMcjJQdQphMmpLZjg1dVVGazNPUVQ1K2VjYzkzUFpaWkFQUUdwZDZSc2NUNGVIUVRCM1E4RWI2NDk3OU0xYUwxeHhibkU2CmRZV3oxZVJBdGxsRmpqSEFvTkE5STlCRTEzR1BFL0g4M0lTTk92TEtsR1pYeXFqeXRKdWl4MTVvNndYQmxJckcKQlhLZVFPaVZtSzJUdGlZQkcxRTR2RGhUWXIzZlQ2bDE0ckY2Ung3M3V5RGtCQU1OU3QyUUdpQjhTd3c0TWxKZQo0ZzdvQ0Z3REFzSHRrSVYwM0VFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNUW8reHZYellteGZwazRFWmZpQkY2TTVzRVRNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSzhid0t0RDcvbElxRTlJS01KbgpuN05rSElyTk0rVHl6MlphTksrdThUdldSM0QzNURmWU5JWTE5Tmhxd2ord09hamRucFJEeWlqbndJNUpialR0Cks3a0p0eWZEUTA2OUwxSGlqanlQRk1RTGdsbTU1U3duZUdJSlUxSkZ3bm4zT0NGVG1pclNoeUxoNkIxYm1TK1oKS2FLSjRkblAwYkkyakV1RWJPNmxrQzA5SmEzUFAwNHNPTWQxY1RXK3JReUl2NHZPVWJEc2FacEFsajhUT09qKwpKcTZPUUZEVlU3WDZmRFZ4NkVpYnNpaXV3bmYwVm5tZFhZRDlrOEl4QSsrMEJUVW5ZTWxIcTRQQld5ckd4a0V0CjVsM2s1TVE4RllqOW5PRkVNOG5lSFpXVFB4WnpuaG00WHZXUTNlNHQwdjdYV1ZWMlRseU1KSTNLRzNaS0k1aEsKVno4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://179326F99DC339E6F5DC5E4F020074EE.yl4.us-east-2.eks.amazonaws.com
  name: demo-app-eks
contexts:
- context:
    cluster: demo-app-eks
    user: jenkins
  name: demo
current-context: demo
kind: Config
preferences: {}
users:
- name: jenkins
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
      - "eks"
      - "get-token"
      - "--cluster-name"
      - "demo-app-eks"

